name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_TRACE: 1
      GIT_TRACE_CURL: 1
      GIT_TRACE_CURL_NO_DATA: 1
    steps:
      - uses: actions/checkout@v2
      - run: cat .git/config
      - run: echo RUNNER_TEMP=$RUNNER_TEMP
      - run: find $RUNNER_TEMP -name .gitconfig -exec cat '{}' ';'
      - run: cat ~/.gitconfig
