name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update -qq
          apt-get install -qq bsdtar
          make --version
          tar --version
          bsdtar --version
