name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t buildenv -f .github/workflows/Dockerfile /var/empty
      - run: docker run -i -v $PWD:/workdir buildenv make -C /workdir
