name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_TRACE: /tmp/trace
      GIT_TRACE_CURL: /tmp/trace.curl
    steps:
      - uses: actions/checkout@v2
      - run: echo $PWD; pwd
      - run: docker build -t buildenv .github/workflows
      - run: docker run -i -v $PWD:/workdir -w /workdir buildenv sh -c "pwd; ls -la"
      - uses: actions/upload-artifact@v2
        with:
          name: trace.txt
          path: /tmp/trace*
