name: ci
on: [push, pull_request]

jobs:
  first:
    runs-on: ubuntu-latest
    env:
      URL: ${{ github.repositoryUrl }}
    steps:
      - run: echo $URL
      - run: pwd
      - run: ls -la
      - run: echo $URL ... ${{ github.repositoryUrl }}
      - run: echo $GITHUB_SERVER_URL ... ${{ github.server_url }}
      - run: git clone --depth=1 $URL .
      - run: ls -la

  build:
    runs-on: ubuntu-latest
    env:
      GIT_TRACE: /tmp/trace
      GIT_TRACE_CURL: /tmp/trace.curl
      GIT_TRACE_CURL_NO_DATA: 1
    steps:
      - uses: actions/checkout@v2
      - run: env | sort
      - run: git config --get http.https://github.com/.extraHeader | base64 -w 0
      - run: |
          git config -l --show-origin
      - run: rm -rf .git .github
      - run: git init .
      - run: git config protocol.version 2
      - run: |
          git config http.https://github.com/.extraHeader "AUTHORIZATION: basic $(printf "x-access-token:%s" "${{ secrets.GITHUB_TOKEN }}" | base64 -w 0)"
      - run: git config --get http.https://github.com/.extraHeader | base64 -w 0
      - run: git remote add origin https://github.com/${{ github.repository }}
      - run: git fetch --verbose --no-tags --prune --depth=1 origin ${{ github.sha }}
      - run: git checkout --force --detach FETCH_HEAD
      - run: echo $PWD; pwd
      - run: docker build -t buildenv .github/workflows
      - run: docker run -i -v $PWD:/workdir -w /workdir buildenv sh -c "pwd; ls -la"
