on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      B: ${{ github.ref_name }}
      R: ${{ github.repository }}
      S: ${{ github.server_url }}
      T: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          git config --global http.$S.extraHeader \
          "AUTHORIZATION: basic $(printf "x-access-token:%s" "$T" | base64 -w 0)"
      - run: git clone --depth=1 --branch=$B $S/$R .
      - run: make
      - run: make check
#     - run: docker build -t buildenv .github/workflows
#     - run: docker run -i -v $PWD:/workdir -w /workdir buildenv sh -c "pwd; ls -la"
